"""Curated Indonesian synonym map and technical-term blacklist."""
from __future__ import annotations

# --------------------------------------------------------------------------- #
# Candidate generation: curated Indonesian synonym map (hand-vetted).
# OMW / WordNet Bahasa was evaluated and rejected: omw-id is largely Malaysian
# WordNet and returns wrong-sense garbage (gampang -> bajingan, pengiriman ->
# benteng, jaringan -> keranjang). Candidates must be sane before the LM ranks.
# --------------------------------------------------------------------------- #
SYNONYMS: dict[str, list[str]] = {
    "membahas": ["membicarakan", "mengulas", "mengupas"],
    "menjelaskan": ["menerangkan", "menguraikan", "memaparkan"],
    "punya": ["memiliki", "mempunyai"],
    "urutan": ["susunan", "tataan"],
    "urutannya": ["susunannya", "tataannya"],
    "diingat": ["dihafal", "dikenang"],
    "sifatnya": ["karakternya", "wataknya"],
    "memahami": ["mengerti", "menguasai"],
    "dipakai": ["digunakan", "dimanfaatkan", "diterapkan"],
    "berhubungan": ["berkaitan", "terkait", "bersangkutan"],
    "misalnya": ["contohnya", "semisal", "umpamanya"],
    "mendapatkan": ["memperoleh", "mendapat"],
    "mengatur": ["mengelola", "menata", "mengurus"],
    "utama": ["pokok", "primer", "terpenting"],
    "sederhana": ["simpel", "ringkas"],
    "menunjukkan": ["memperlihatkan", "menampilkan"],
    "contohnya": ["misalnya", "umpamanya"],
    "menentukan": ["menetapkan", "memutuskan"],
    "jalur": ["rute", "lintasan"],
    "tujuan": ["sasaran", "arah"],
    "terasa": ["dirasakan", "kelihatan"],
    "pengguna": ["pemakai"],
    "mencakup": ["meliputi", "melingkupi"],
    "digabung": ["disatukan", "dilebur", "dikombinasikan"],
    "bagian": ["komponen", "elemen", "sisi"],
    "mengecek": ["memeriksa", "memantau"],
    "mendeteksi": ["mengenali", "menemukan"],
    "mengirim": ["menyalurkan", "meneruskan"],
    "bentuk": ["wujud", "format"],
    "media": ["medium", "perantara", "sarana"],
    "cahaya": ["sinar"],
    "melewati": ["melalui", "melintasi"],
    "tahap": ["tahapan", "langkah", "fase"],
    "tugas": ["peran", "fungsi"],
    "penting": ["krusial", "signifikan", "vital"],
    "berada": ["terletak", "berlokasi"],
    "berbeda": ["berlainan", "beda"],
    "fungsi": ["peran", "kegunaan"],
    "menangani": ["mengurus", "mengelola"],
    "hubungan": ["kaitan", "relasi", "keterkaitan"],
    "istilah": ["terminologi", "sebutan"],
    "terlihat": ["tampak", "kelihatan"],
    "melihat": ["menyimak", "mengamati"],
    "pembagian": ["pengelompokan", "pemilahan"],
    "berdasarkan": ["berdasar"],
    "gampang": ["mudah"],
    "mengingatnya": ["menghafalnya"],
    "saling": ["satu sama lain", "timbal balik"],
    "melengkapi": ["menyempurnakan", "menunjang"],
    "tambahan": ["ekstra", "pelengkap"],
    "berubah": ["bertransformasi", "berganti"],
    "proses": ["tahapan", "prosedur", "alur"],
    "berkaitan": ["berhubungan", "terkait"],
    "dasar": ["asas", "landasan"],
    "pemahaman": ["pengertian", "pengetahuan"],
    "topik": ["tema", "bahasan"],
    "pengiriman": ["penyaluran"],
    "dikirim": ["disalurkan", "diteruskan"],
    "kalau": ["jika", "bila"],
    "cuma": ["hanya"],
    "butuh": ["memerlukan", "membutuhkan"],
    "berupa": ["berbentuk", "berwujud"],
    "disusun": ["ditata", "dirangkai"],
    "dilepas": ["dihilangkan", "dicopot"],
    "disebut": ["dinamakan", "dikenal sebagai"],
    "dibalik": ["dikembalikan", "dibalikkan"],
    "terbayang": ["tergambar"],
    "setelah": ["sesudah", "seusai"],
    "soal": ["tentang", "perihal"],
    "jadi": ["menjadi"],
    "bisa": ["dapat"],
    "tiap": ["setiap"],
    "sebuah": ["suatu"],
    "saat": ["ketika", "waktu"],
    "tapi": ["namun", "tetapi"],
    "keterlambatan": ["kelambatan"],
    "benar-benar": ["betul-betul", "sungguh"],
    "pembagiannya": ["pengelompokannya"],
    "fondasi": ["landasan", "pondasi"],
    "spesifik": ["khusus", "tertentu"],
    "perubahan": ["pergantian", "transformasi"],
    "perangkat": ["piranti"],
    "listrik": ["elektrik"],
    "layanan": ["servis"],
    "menerjemahkan": ["mengonversi", "mengubah"],
}

# Technical vocabulary that must never be substituted.
BLACKLIST: set[str] = {
    "osi", "tcp", "ip", "udp", "http", "dns", "dhcp", "ftp", "ssh", "qos",
    "mac", "nic", "ethernet", "physical", "link", "network", "transport",
    "session", "presentation", "application", "internet", "access", "layer",
    "segment", "packet", "frame", "bits", "bit", "port", "address", "routing",
    "subnetting", "encapsulation", "decapsulation", "fiber", "optic",
    "wireless", "website", "domain", "error", "traffic", "remote", "user",
    "data", "reliable", "quality", "service", "video", "youtube", "mnemonic",
}
