"""Curated Indonesian synonym map and technical-term blacklist."""
from __future__ import annotations

# --------------------------------------------------------------------------- #
# Candidate generation: curated Indonesian synonym map (hand-vetted).
# OMW / WordNet Bahasa was evaluated and rejected: omw-id is largely Malaysian
# WordNet and returns wrong-sense garbage (gampang -> bajingan, pengiriman ->
# benteng, jaringan -> keranjang). Candidates must be sane before the LM ranks.
# --------------------------------------------------------------------------- #
SYNONYMS: dict[str, list[str]] = {
    "membahas": ["membicarakan", "mengulas", "mengupas"],
    "menjelaskan": ["menerangkan", "menguraikan", "memaparkan"],
    "punya": ["memiliki", "mempunyai"],
    "urutan": ["susunan", "tataan"],
    "urutannya": ["susunannya", "tataannya"],
    "diingat": ["dihafal", "dikenang"],
    "sifatnya": ["karakternya", "wataknya"],
    "memahami": ["mengerti", "menguasai"],
    "dipakai": ["digunakan", "dimanfaatkan", "diterapkan"],
    "berhubungan": ["berkaitan", "terkait", "bersangkutan"],
    "misalnya": ["contohnya", "semisal", "umpamanya"],
    "mendapatkan": ["memperoleh", "mendapat"],
    "mengatur": ["mengelola", "menata", "mengurus"],
    "utama": ["pokok", "primer", "terpenting"],
    "sederhana": ["simpel", "ringkas"],
    "menunjukkan": ["memperlihatkan", "menampilkan"],
    "contohnya": ["misalnya", "umpamanya"],
    "menentukan": ["menetapkan", "memutuskan"],
    "jalur": ["rute", "lintasan"],
    "tujuan": ["sasaran", "arah"],
    "terasa": ["dirasakan", "kelihatan"],
    "pengguna": ["pemakai"],
    "mencakup": ["meliputi", "melingkupi"],
    "digabung": ["disatukan", "dilebur", "dikombinasikan"],
    "bagian": ["komponen", "elemen", "sisi"],
    "mengecek": ["memeriksa", "memantau"],
    "mendeteksi": ["mengenali", "menemukan"],
    "mengirim": ["menyalurkan", "meneruskan"],
    "bentuk": ["wujud", "format"],
    "media": ["medium", "perantara", "sarana"],
    "cahaya": ["sinar"],
    "melewati": ["melalui", "melintasi"],
    "tahap": ["tahapan", "langkah", "fase"],
    "tugas": ["peran", "fungsi"],
    "penting": ["krusial", "signifikan", "vital"],
    "berada": ["terletak", "berlokasi"],
    "berbeda": ["berlainan", "beda"],
    "fungsi": ["peran", "kegunaan"],
    "menangani": ["mengurus", "mengelola"],
    "hubungan": ["kaitan", "relasi", "keterkaitan"],
    "istilah": ["terminologi", "sebutan"],
    "terlihat": ["tampak", "kelihatan"],
    "melihat": ["menyimak", "mengamati"],
    "pembagian": ["pengelompokan", "pemilahan"],
    "berdasarkan": ["berdasar"],
    "gampang": ["mudah"],
    "mengingatnya": ["menghafalnya"],
    "saling": ["satu sama lain", "timbal balik"],
    "melengkapi": ["menyempurnakan", "menunjang"],
    "tambahan": ["ekstra", "pelengkap"],
    "berubah": ["bertransformasi", "berganti"],
    "proses": ["tahapan", "prosedur", "alur"],
    "berkaitan": ["berhubungan", "terkait"],
    "dasar": ["asas", "landasan"],
    "pemahaman": ["pengertian", "pengetahuan"],
    "topik": ["tema", "bahasan"],
    "pengiriman": ["penyaluran"],
    "dikirim": ["disalurkan", "diteruskan"],
    "kalau": ["jika", "bila"],
    "cuma": ["hanya"],
    "butuh": ["memerlukan", "membutuhkan"],
    "berupa": ["berbentuk", "berwujud"],
    "disusun": ["ditata", "dirangkai"],
    "dilepas": ["dihilangkan", "dicopot"],
    "disebut": ["dinamakan", "dikenal sebagai"],
    "dibalik": ["dikembalikan", "dibalikkan"],
    "terbayang": ["tergambar"],
    "setelah": ["sesudah", "seusai"],
    "soal": ["tentang", "perihal"],
    "jadi": ["menjadi"],
    "bisa": ["dapat"],
    "tiap": ["setiap"],
    "sebuah": ["suatu"],
    "saat": ["ketika", "waktu"],
    "tapi": ["namun", "tetapi"],
    "keterlambatan": ["kelambatan"],
    "benar-benar": ["betul-betul", "sungguh"],
    "pembagiannya": ["pengelompokannya"],
    "fondasi": ["landasan", "pondasi"],
    "spesifik": ["khusus", "tertentu"],
    "perubahan": ["pergantian", "transformasi"],
    "perangkat": ["piranti"],
    "listrik": ["elektrik"],
    "menerjemahkan": ["mengonversi", "mengubah"],
    "menggunakan": ["memakai", "menerapkan", "memanfaatkan"],
    "membuat": ["menciptakan", "merancang", "membangun"],
    "membantu": ["menolong", "menunjang", "memfasilitasi"],
    "banyak": ["beragam", "berbagai", "sejumlah"],
    "sulit": ["sukar", "rumit", "pelik"],
    "mudah": ["gampang", "simpel", "ringkas"],
    "cepat": ["kilat", "gesit", "pesat"],
    "lambat": ["perlahan", "lamban"],
    "besar": ["luas", "signifikan", "masif"],
    "kecil": ["minor", "terbatas", "sempit"],
    "tinggi": ["unggul", "meningkat", "terangkat"],
    "rendah": ["minim", "terbatas", "sedikit"],
    "sering": ["kerap", "lazim", "berulang"],
    "jarang": ["langka", "segelintir"],
    "sangat": ["amat", "begitu", "sungguh"],
    "cukup": ["memadai", "mencukupi"],
    "memiliki": ["mempunyai", "mengantongi"],
    "berfungsi": ["berperan", "berguna"],
    "menghasilkan": ["membuahkan", "menciptakan"],
    "menyatakan": ["mengemukakan", "menyampaikan"],
    "menyebabkan": ["mengakibatkan", "memicu"],
    "memulai": ["mengawali", "menginisiasi"],
    "menyelesaikan": ["menuntaskan", "merampungkan"],
    "meneliti": ["mengkaji", "menginvestigasi"],
    "menemukan": ["mendapati", "menjumpai"],
    "berjalan": ["berlangsung", "berproses"],
    "menerima": ["memperoleh", "mendapat"],
    "memberi": ["menyediakan", "menghadirkan"],
    "memberikan": ["menyajikan", "menyediakan"],
    "mengembangkan": ["meningkatkan", "memperluas"],
    "memperbaiki": ["menyempurnakan", "membenahi"],
    "memperjelas": ["menerangkan", "menguraikan"],
    "kesimpulan": ["konklusi", "rangkuman"],
    "penelitian": ["studi", "kajian", "riset"],
    "metode": ["pendekatan", "metodologi", "prosedur"],
    "hasil": ["temuan", "keluaran", "dampak"],
    "masalah": ["kendala", "hambatan", "persoalan"],
    "solusi": ["pemecahan", "jalan keluar"],
    "kemungkinan": ["peluang", "potensi"],
    "faktor": ["elemen", "aspek", "komponen"],
    "alasan": ["dalih", "pertimbangan"],
    "cara": ["langkah", "teknik", "metode"],
}

# Technical vocabulary that must never be substituted (Indonesian / networking context).
BLACKLIST: set[str] = {
    "osi", "tcp", "ip", "udp", "http", "dns", "dhcp", "ftp", "ssh", "qos",
    "mac", "nic", "ethernet", "physical", "link", "network", "transport",
    "session", "presentation", "application", "internet", "access", "layer",
    "segment", "packet", "frame", "bits", "bit", "port", "address", "routing",
    "subnetting", "encapsulation", "decapsulation", "fiber", "optic",
    "wireless", "website", "domain", "error", "traffic", "remote", "user",
    "data", "reliable", "quality", "service", "video", "youtube", "mnemonic",
}

SYNONYMS_ID = SYNONYMS
BLACKLIST_ID = BLACKLIST

# --------------------------------------------------------------------------- #
# Curated English synonym map (academic & general prose).
# --------------------------------------------------------------------------- #
SYNONYMS_EN: dict[str, list[str]] = {
    "discuss": ["examine", "explore", "address", "review"],
    "discusses": ["examines", "explores", "addresses", "reviews"],
    "discussed": ["examined", "explored", "addressed", "reviewed"],
    "explain": ["describe", "clarify", "illustrate", "outline"],
    "explains": ["describes", "clarifies", "illustrates", "outlines"],
    "explained": ["described", "clarified", "illustrated", "outlined"],
    "understand": ["comprehend", "grasp", "interpret"],
    "understands": ["comprehends", "grasps", "interprets"],
    "show": ["demonstrate", "illustrate", "exhibit", "reveal"],
    "shows": ["demonstrates", "illustrates", "exhibits", "reveals"],
    "showed": ["demonstrated", "illustrated", "exhibited", "revealed"],
    "shown": ["demonstrated", "illustrated", "revealed"],
    "provide": ["supply", "offer", "deliver", "furnish"],
    "provides": ["supplies", "offers", "delivers", "furnishes"],
    "provided": ["supplied", "offered", "delivered", "furnished"],
    "important": ["crucial", "essential", "significant", "vital"],
    "crucial": ["vital", "essential", "critical"],
    "essential": ["vital", "indispensable", "crucial"],
    "simple": ["straightforward", "concise", "elementary"],
    "main": ["primary", "principal", "chief", "central"],
    "primary": ["main", "principal", "foremost"],
    "different": ["distinct", "diverse", "varied"],
    "method": ["approach", "technique", "procedure"],
    "methods": ["approaches", "techniques", "procedures"],
    "manage": ["handle", "coordinate", "oversee"],
    "manages": ["handles", "coordinates", "oversees"],
    "determine": ["establish", "identify", "specify"],
    "determines": ["establishes", "identifies", "specifies"],
    "achieve": ["accomplish", "attain", "realize"],
    "achieves": ["accomplishes", "attains", "realizes"],
    "require": ["necessitate", "demand", "call for"],
    "requires": ["necessitates", "demands", "calls for"],
    "allow": ["enable", "permit", "facilitate"],
    "allows": ["enables", "permits", "facilitates"],
    "build": ["construct", "develop", "assemble"],
    "create": ["generate", "produce", "establish"],
    "creates": ["generates", "produces", "establishes"],
    "consider": ["evaluate", "examine", "regard"],
    "considers": ["evaluates", "examines", "regards"],
    "result": ["outcome", "consequence", "finding"],
    "results": ["outcomes", "consequences", "findings"],
    "purpose": ["objective", "goal", "aim"],
    "component": ["element", "constituent", "part"],
    "components": ["elements", "constituents", "parts"],
    "process": ["procedure", "workflow", "operation"],
    "send": ["transmit", "dispatch", "forward"],
    "sends": ["transmits", "dispatches", "forwards"],
    "sent": ["transmitted", "dispatched", "forwarded"],
    "receive": ["obtain", "acquire", "gather"],
    "receives": ["obtains", "acquires", "gathers"],
    "received": ["obtained", "acquired", "collected"],
    "start": ["commence", "initiate", "begin"],
    "starts": ["commences", "initiates", "begins"],
    "finish": ["conclude", "complete", "finalize"],
    "check": ["verify", "inspect", "examine"],
    "checks": ["verifies", "inspects", "examines"],
    "connect": ["link", "join", "couple"],
    "connects": ["links", "joins", "couples"],
    "improve": ["enhance", "refine", "boost"],
    "improves": ["enhances", "refines", "boosts"],
    "reduce": ["decrease", "diminish", "lessen"],
    "reduces": ["decreases", "diminishes", "lessens"],
    "increase": ["expand", "augment", "elevate"],
    "increases": ["expands", "augments", "elevates"],
    "change": ["alter", "modify", "transform"],
    "changes": ["alters", "modifies", "transforms"],
    "section": ["segment", "portion", "division"],
    "rapid": ["swift", "speedy", "brisk"],
    "accurate": ["precise", "exact", "correct"],
    "complex": ["intricate", "elaborate", "sophisticated"],
    "effective": ["productive", "efficacious", "potent"],
    "clear": ["lucid", "apparent", "evident"],
    "fundamental": ["basic", "underlying", "core"],
    "suitable": ["appropriate", "fitting", "apt"],
    "sufficient": ["adequate", "ample", "enough"],
    "observe": ["notice", "detect", "witness"],
    "indicates": ["signifies", "denotes", "suggests"],
    "indicate": ["signify", "denote", "suggest"],
    "maintain": ["sustain", "preserve", "uphold"],
    "maintains": ["sustains", "preserves", "upholds"],
    "focus": ["concentrate", "center"],
    "broad": ["wide", "extensive", "comprehensive"],
    "modern": ["contemporary", "current", "recent"],
    "traditional": ["conventional", "customary"],
    "challenge": ["difficulty", "obstacle", "hurdle"],
    "challenges": ["difficulties", "obstacles", "hurdles"],
    "solution": ["remedy", "resolution", "answer"],
    "solutions": ["remedies", "resolutions", "answers"],
    "impact": ["influence", "effect", "consequence"],
    "role": ["function", "part", "task"],
    "factor": ["element", "determinant", "aspect"],
    "factors": ["elements", "determinants", "aspects"],
    "category": ["classification", "grouping"],
    "concept": ["notion", "idea", "principle"],
    "concepts": ["notions", "ideas", "principles"],
    "feature": ["characteristic", "attribute", "trait"],
    "features": ["characteristics", "attributes", "traits"],
    "issue": ["problem", "dilemma", "complication"],
    "issues": ["problems", "dilemmas", "complications"],
    "perform": ["execute", "carry out", "conduct"],
    "performs": ["executes", "carries out", "conducts"],
    "mention": ["note", "state", "remark"],
    "obtain": ["acquire", "secure", "procure"],
    "ensure": ["guarantee", "assure", "confirm"],
    "ensures": ["guarantees", "assures", "confirms"],
    "support": ["bolster", "reinforce", "sustain"],
    "supports": ["bolsters", "reinforces", "sustains"],
    "prevent": ["avert", "hinder", "preclude"],
    "prevents": ["averts", "hinders", "precludes"],
    "choose": ["select", "opt for", "pick"],
    "display": ["exhibit", "showcase", "present"],
    "displays": ["exhibits", "showcases", "presents"],
    "define": ["specify", "delineate", "characterize"],
    "defines": ["specifies", "delineates", "characterizes"],
    "investigate": ["examine", "scrutinize", "explore"],
    "combine": ["merge", "integrate", "synthesize"],
    "combines": ["merges", "integrates", "synthesizes"],
    "assist": ["aid", "help", "support"],
    "assists": ["aids", "helps", "supports"],
    "represent": ["signify", "embody", "stand for"],
    "represents": ["signifies", "embodies", "stands for"],
    "utilize": ["use", "employ", "apply"],
    "utilizes": ["uses", "employs", "applies"],
    "utilized": ["used", "employed", "applied"],
    "reveal": ["uncover", "disclose", "expose"],
    "reveals": ["uncovers", "discloses", "exposes"],
    "highlight": ["emphasize", "underscore", "accentuate"],
    "highlights": ["emphasizes", "underscores", "accentuates"],
    "evaluate": ["assess", "appraise", "gauge"],
    "evaluates": ["assesses", "appraises", "gauges"],
    "implement": ["apply", "execute", "enact"],
    "implements": ["applies", "executes", "enacts"],
    "identify": ["recognize", "distinguish", "pinpoint"],
    "identifies": ["recognizes", "distinguishes", "pinpoints"],
    "clarify": ["elucidate", "explain", "illuminate"],
    "summarize": ["recap", "encapsulate", "outline"],
    "generate": ["produce", "create", "yield"],
    "generates": ["produces", "creates", "yields"],
    "illustrate": ["exemplify", "demonstrate", "depict"],
    "illustrates": ["exemplifies", "demonstrates", "depicts"],
    "emphasize": ["stress", "underscore", "highlight"],
    "emphasizes": ["stresses", "underscores", "highlights"],
    "facilitate": ["expedite", "ease", "assist"],
    "facilitates": ["expedites", "eases", "assists"],
    "conclude": ["deduce", "infer", "wrap up"],
    "concludes": ["deduces", "infers", "wraps up"],
    "difficult": ["challenging", "hard", "demanding", "arduous"],
    "difficulty": ["challenge", "hurdle", "complication"],
    "easy": ["simple", "straightforward", "uncomplicated"],
    "easily": ["readily", "effortlessly", "smoothly"],
    "use": ["utilize", "apply", "employ", "adopt"],
    "uses": ["utilizes", "applies", "employs", "adopts"],
    "used": ["utilized", "applied", "employed", "adopted"],
    "using": ["utilizing", "applying", "employing"],
    "make": ["produce", "create", "construct", "form"],
    "makes": ["produces", "creates", "renders"],
    "made": ["produced", "created", "formed"],
    "making": ["producing", "creating", "forming"],
    "help": ["assist", "aid", "facilitate", "support"],
    "helps": ["assists", "aids", "facilitates", "supports"],
    "helped": ["assisted", "aided", "facilitated", "supported"],
    "helping": ["assisting", "aiding", "facilitating"],
    "find": ["discover", "uncover", "identify", "locate"],
    "finds": ["discovers", "uncovers", "identifies"],
    "found": ["discovered", "uncovered", "identified"],
    "finding": ["discovery", "result", "outcome"],
    "findings": ["discoveries", "results", "outcomes"],
    "study": ["research", "investigation", "analysis", "inquiry"],
    "studies": ["investigations", "analyses", "inquiries"],
    "paper": ["article", "manuscript", "report", "document"],
    "system": ["framework", "structure", "scheme", "setup"],
    "systems": ["frameworks", "structures", "schemes"],
    "large": ["substantial", "significant", "considerable", "extensive"],
    "small": ["compact", "modest", "minor", "limited"],
    "high": ["elevated", "considerable", "substantial", "pronounced"],
    "low": ["minimal", "reduced", "modest", "diminished"],
    "often": ["frequently", "commonly", "regularly", "typically"],
    "usually": ["typically", "generally", "commonly", "ordinarily"],
    "rarely": ["seldom", "infrequently", "scarcely"],
    "quickly": ["rapidly", "swiftly", "promptly"],
    "slowly": ["gradually", "steadily"],
    "clearly": ["evidently", "plainly", "manifestly"],
    "good": ["favorable", "advantageous", "beneficial", "sound"],
    "bad": ["unfavorable", "adverse", "detrimental"],
    "great": ["substantial", "remarkable", "considerable"],
    "strong": ["robust", "solid", "potent", "resilient"],
    "weak": ["fragile", "vulnerable", "feeble"],
    "lead": ["guide", "direct", "steer", "cause"],
    "leads": ["guides", "directs", "steers"],
    "led": ["guided", "directed"],
    "leading": ["guiding", "directing", "steering"],
    "present": ["introduce", "exhibit", "display", "offer"],
    "presents": ["introduces", "exhibits", "displays", "offers"],
    "presented": ["introduced", "exhibited", "displayed"],
    "presenting": ["introducing", "exhibiting", "displaying"],
    "include": ["encompass", "incorporate", "comprise", "contain"],
    "includes": ["encompasses", "incorporates", "comprises", "contains"],
    "included": ["encompassed", "incorporated", "comprised"],
    "including": ["encompassing", "incorporating", "comprising"],
    "examine": ["investigate", "scrutinize", "inspect", "analyze"],
    "examines": ["investigates", "scrutinizes", "inspects", "analyzes"],
    "examined": ["investigated", "scrutinized", "inspected"],
    "examining": ["investigating", "scrutinizing", "inspecting"],
    "demonstrate": ["illustrate", "exhibit", "substantiate"],
    "demonstrates": ["illustrates", "exhibits", "substantiates"],
    "demonstrated": ["illustrated", "exhibited", "substantiated"],
    "demonstrating": ["illustrating", "exhibiting", "substantiating"],
    "suggest": ["propose", "indicate", "imply", "recommend"],
    "suggests": ["proposes", "indicates", "implies", "recommends"],
    "suggested": ["proposed", "indicated", "implied"],
    "suggesting": ["proposing", "indicating", "implying"],
    "various": ["diverse", "manifold", "varied", "assorted"],
    "numerous": ["multiple", "many", "countless", "copious"],
    "particular": ["specific", "distinct", "individual"],
    "particularly": ["especially", "notably", "specifically"],
    "significant": ["substantial", "notable", "meaningful", "momentous"],
    "significantly": ["substantially", "notably", "markedly", "considerably"],
    "essentially": ["fundamentally", "primarily", "at core"],
    "accurately": ["precisely", "faithfully", "rigorously"],
    "reliable": ["dependable", "trustworthy", "consistent", "stable"],
    "reliably": ["dependably", "consistently", "stably"],
    "simply": ["merely", "straightforwardly"],
    "novel": ["innovative", "fresh", "groundbreaking", "unconventional"],
    "rapidly": ["swiftly", "fast", "speedily"],
    "major": ["principal", "key", "predominant", "central"],
    "minor": ["secondary", "subordinate", "peripheral"],
    "vital": ["critical", "crucial", "imperative", "essential"],
    "critical": ["vital", "crucial", "decisive", "pivotal"],
    "key": ["pivotal", "central", "paramount"],
    "basic": ["rudimentary", "fundamental", "underlying", "core"],
    "unique": ["distinctive", "singular", "exclusive"],
    "common": ["prevalent", "widespread", "frequent"],
    "rare": ["scarce", "infrequent", "uncommon"],
    "obvious": ["evident", "apparent", "manifest"],
    "obviously": ["evidently", "apparently", "clearly"],
    "potential": ["prospective", "possible", "promising"],
    "potentially": ["possibly", "prospectively"],
    "actual": ["genuine", "tangible", "real", "concrete"],
    "actually": ["in fact", "genuinely", "really"],
    "similar": ["comparable", "akin", "analogous", "parallel"],
    "difference": ["distinction", "disparity", "divergence", "variance"],
    "differences": ["distinctions", "disparities", "divergences"],
    "constant": ["invariable", "continuous", "steady", "unwavering"],
    "constantly": ["continuously", "invariably", "steadily"],
    "efficient": ["productive", "effective", "streamlined"],
    "efficiently": ["productively", "effectively"],
    "efficiency": ["productivity", "effectiveness"],
    "valuable": ["worthwhile", "invaluable", "beneficial"],
    "standard": ["benchmark", "norm", "criterion", "convention"],
    "typical": ["representative", "characteristic"],
    "extensive": ["comprehensive", "broad", "vast", "sweeping"],
    "extensively": ["comprehensively", "widely", "broadly"],
    "complete": ["comprehensive", "exhaustive", "thorough", "total"],
    "completely": ["entirely", "wholly", "fully", "thoroughly"],
    "immediate": ["prompt", "instant", "direct", "swift"],
    "immediately": ["promptly", "instantly", "directly"],
    "initial": ["preliminary", "introductory", "starting", "earliest"],
    "initially": ["preliminarily", "at first", "originally"],
    "final": ["concluding", "ultimate", "eventual"],
    "finally": ["ultimately", "eventually", "in conclusion"],
    "furthermore": ["moreover", "in addition", "additionally"],
    "moreover": ["furthermore", "in addition", "besides"],
    "however": ["nevertheless", "nonetheless", "conversely"],
    "therefore": ["consequently", "thus", "accordingly", "hence"],
    "consequently": ["therefore", "as a result", "thus", "accordingly"],
    "meanwhile": ["simultaneously", "at the same time"],
    "specifically": ["expressly", "explicitly", "particularly"],
    "similarly": ["likewise", "correspondingly"],
}

BLACKLIST_EN: set[str] = {
    "tcp", "ip", "udp", "http", "https", "dns", "dhcp", "ftp", "ssh", "qos",
    "mac", "nic", "ethernet", "router", "switch", "gateway", "osi", "packet",
    "packets", "frame", "frames", "bit", "bits", "byte", "bytes", "cpu", "ram",
    "gpu", "latex", "tex", "api", "url", "json", "html", "css", "sql", "ai",
    "ml", "nlp", "server", "client", "host", "protocol", "port", "socket",
}


def get_synonyms(lang: str = "id") -> dict[str, list[str]]:
    """Return the synonym dictionary for the specified language ('id' or 'en')."""
    return SYNONYMS_EN if lang.lower() == "en" else SYNONYMS_ID


def get_blacklist(lang: str = "id") -> set[str]:
    """Return the technical blacklist set for the specified language ('id' or 'en')."""
    return BLACKLIST_EN if lang.lower() == "en" else BLACKLIST_ID

